version: '3.8'

services:
  service_docs:
    build:
      context: .
      dockerfile: DockerFileDoc
      
    ports:
      - "3012:8080"

  service_dev:
    build:
      context: .
      dockerfile: DockerFileApi
    environment:
      MONGODB_URI: mongodb://test:abc123@localhost:27017/mtp_open_data
      JWT_SECRET: secret
    ports:
      - "3014:3000"
