version: '3.8'

services:
  service_docs:
    build:
      context: .
      dockerfile: DockerFileDoc
      
    ports:
      - "3012:8080"

  service_api:
    build:
      context: .
      dockerfile: DockerFileApi
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: secret
    ports:
      - "3014:3000"
    networks:
      - mongo
networks:
  mongo:
    external: true
