version: '3.8'
services:
  # Config servers
  configsvr:
    image: mongo:4.4
    command: mongod --configsvr --replSet configrs --bind_ip_all --port 27019
    volumes:
      - configsvrdata:/data/db
    networks:
      - dc1

  # Shard 1 servers (simulating DC1)
  shard1svr:
    image: mongo:4.4
    command: mongod --shardsvr --replSet shard1 --bind_ip_all --port 27018
    volumes:
      - shard1data:/data/db
    networks:
      - dc1

  # Shard 2 servers (simulating DC2)
  shard2svr:
    image: mongo:4.4
    command: mongod --shardsvr --replSet shard2 --bind_ip_all --port 27020
    volumes:
      - shard2data:/data/db
    networks:
      - dc2

  # Mongos routers
  mongos:
    image: mongo:4.4
    command: mongos --configdb configrs/configsvr:27019 --bind_ip_all --port 27017
    depends_on:
      - configsvr
    networks:
      - dc1
      - dc2
      - dc3
    ports:
      - 27017:27017

networks:
  dc1:
  dc2:
  dc3:

volumes:
  configsvrdata:
  shard1data:
  shard2data:
