version: '3.8'

networks:
  - DC1
  - DC2
  - DC3

services:
  # Config servers
  DC1-Config-srv:
    image: mongo:4.4
    command: mongod --configsvr --replSet configrs --bind_ip_all --port 27019
    volumes:
      - DC1-Config-srv:/data/db
    networks:
      - DC1
