version: '3.8'

services:
  # Config servers
  DC1-Config-srv:
    image: mongo:latest
    container_name: DC1-Config-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/configsrv.conf']
    volumes:
      - DC1-Config-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/configsrv.conf:/etc/mongo/configsrv.conf

  DC2-Config-srv:
    image: mongo:latest
    container_name: DC2-Config-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/configsrv.conf']
    volumes:
      - DC2-Config-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/configsrv.conf:/etc/mongo/configsrv.conf

  DC3-Config-srv:
    image: mongo:latest
    container_name: DC3-Config-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/configsrv.conf']
    volumes:
      - DC3-Config-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/configsrv.conf:/etc/mongo/configsrv.conf

  # Shard 1 servers
  DC1-Shard1-srv:
    image: mongo:latest
    container_name: DC1-Shard1-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard1.conf']
    volumes:
      - DC1-Shard1-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard1.conf:/etc/mongo/shard1.conf

  DC2-Shard1-srv:
    image: mongo:latest
    container_name: DC2-Shard1-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard1.conf']
    volumes:
      - DC2-Shard1-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard1.conf:/etc/mongo/shard1.conf

  DC3-Shard1-srv:
    image: mongo:latest
    container_name: DC3-Shard1-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard1.conf']
    volumes:
      - DC3-Shard1-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard1.conf:/etc/mongo/shard1.conf

  # Shard 2 servers
  DC1-Shard2-srv:
    image: mongo:latest
    container_name: DC1-Shard2-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard2.conf']
    volumes:
      - DC1-Shard2-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard2.conf:/etc/mongo/shard2.conf

  DC2-Shard2-srv:
    image: mongo:latest
    container_name: DC2-Shard2-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard2.conf']
    volumes:
      - DC2-Shard2-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard2.conf:/etc/mongo/shard2.conf

  DC3-Shard2-srv:
    image: mongo:latest
    container_name: DC3-Shard2-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard2.conf']
    volumes:
      - DC3-Shard2-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard2.conf:/etc/mongo/shard2.conf

  # Shard 3 servers
  DC1-Shard3-srv:
    image: mongo:latest
    container_name: DC1-Shard3-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard3.conf']
    volumes:
      - DC1-Shard3-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard3.conf:/etc/mongo/shard3.conf

  DC2-Shard3-srv:
    image: mongo:latest
    container_name: DC2-Shard3-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard3.conf']
    volumes:
      - DC2-Shard3-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard3.conf:/etc/mongo/shard3.conf

  DC3-Shard3-srv:
    image: mongo:latest
    container_name: DC3-Shard3-srv
    entrypoint: ['mongod', '--config', '/etc/mongo/shard3.conf']
    volumes:
      - DC3-Shard3-srv:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/shard3.conf:/etc/mongo/shard3.conf

  # Mongos routers
  DC1-Mongos:
    image: mongo:latest
    container_name: DC1-Mongos
    entrypoint: ['mongos', '--config', '/etc/mongo/mongos.conf']
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
    depends_on:
      - DC1-Config-srv
      - DC2-Config-srv
      - DC3-Config-srv
    volumes:
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/mongos.conf:/etc/mongo/mongos.conf
      - ./config/setup-cluster.js:/etc/mongo/setup-cluster.js
      - ./config/setup-admin.js:/etc/mongo/setup-admin.js
      - ./config/get-repartition.js:/etc/mongo/get-repartition.js
    ports:
      - 27017:27017

  DC2-Mongos:
    image: mongo:latest
    container_name: DC2-Mongos
    entrypoint: ['mongos', '--config', '/etc/mongo/mongos.conf']
    depends_on:
      - DC1-Config-srv
      - DC2-Config-srv
      - DC3-Config-srv
    volumes:
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/mongos.conf:/etc/mongo/mongos.conf
    ports:
      - 27018:27017

  DC3-Mongos:
    image: mongo:latest
    container_name: DC3-Mongos
    entrypoint: ['mongos', '--config', '/etc/mongo/mongos.conf']
    depends_on:
      - DC1-Config-srv
      - DC2-Config-srv
      - DC3-Config-srv
    volumes:
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
      - ./config/mongos.conf:/etc/mongo/mongos.conf

    ports:
      - 27019:27017

volumes:
  DC1-Config-srv:
  DC2-Config-srv:
  DC3-Config-srv:
  DC1-Shard1-srv:
  DC2-Shard1-srv:
  DC3-Shard1-srv:
  DC1-Shard2-srv:
  DC2-Shard2-srv:
  DC3-Shard2-srv:
  DC1-Shard3-srv:
  DC2-Shard3-srv:
  DC3-Shard3-srv:
