name: Check code quality

on: 
  push: 
    branches: 
      - '*'
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Lint code
        run: |
          cd backend
          npm run lint-ci

      - name: Check package dependencies
        run: |
          cd backend
          npm audit