name: Check code quality

on: 
  push: 
    branches: 
      - '*'
jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Lint code
        run: |
          cd backend
          npm run lint-ci

      - name: Check package dependencies
        run: |
          cd backend
          npm audit